baseURL = 'https://jacobshirley.tech/'
languageCode = 'en-us'
title = 'Jacob Shirley'
theme = 'jake'

[[menus.main]]
name = 'Github'
url = 'https://github.com/jacobshirley'
weight = 10
target = "_blank"

[[menus.main]]
name = 'Contact'
url = 'mailto:jakeshirley2@gmail.com'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"